import mongoose from "mongoose";
import Child from "./ChildSchema.js";
import Parent from "./ParentSchema.js";
import Family from "./FamilySchema.js";
import Sibling from "./SiblingSchema.js";
import Stats from "./StatSchema.js";
import User from "./UserSchema.js";

// mongoDB connection string
const mongoURI = ""; // replace this here


const families = [
  {
    nanay: {
      pangalan: "Maria Santos",
      palayaw: "Marian",
      kasarian: "Female",
      edad: 36,
      birthday: "1987-05-20",
      lugarNgKapanganakan: "Cebu City",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "University of San Carlos",
      tirahan: "Cebu City",
      probinsya: "Cebu",
      trabaho: "Teacher",
      kita: 20000,
      skillTraining: "Educational Development",
      skills: "Teaching, Counseling",
      dokumento: ["Voter's ID", "PhilHealth"],
    },
    tatay: {
      pangalan: "Juan Santos",
      palayaw: "Johnny",
      kasarian: "Male",
      edad: 40,
      birthday: "1983-01-15",
      lugarNgKapanganakan: "Cebu City",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Cebu Technical School",
      tirahan: "Cebu City",
      probinsya: "Cebu",
      trabaho: "Construction Worker",
      kita: 15000,
      skillTraining: "Carpentry",
      skills: "Masonry, Plumbing",
      dokumento: ["Driver's License", "SSS"],
    },
    child: {
      program: "Community Based Program",
      caseNo: 1001,
      pangalan: "Emmanuel Santos",
      edad: 11,
      birthday: "2012-03-11",
      relihiyon: "Christian",
      antasNgPaaralan: "Elementary",
      palayaw: "Emman",
      kasarian: "Male",
      lugarNgKapanganakan: "Cebu City",
      hulingPaaralangPinasukan: "Cebu Elementary School",
      tirahan: "Cebu City",
      problema: ["Asthma"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "MMR",
      initialNaItsura: ["Short hair", "Tan skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Cebu LGU" },
      nanay: "Maria Santos",
      tatay: "Juan Santos",
      kapatid: ["Grace Santos", "Miguel Santos"], // Siblings will be inserted separately
      goalsAchieved: ["Finished school year"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Grace Santos",
        kasarian: "Female",
        edad: 9,
        antasNgPaaralan: "Elementary",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "Miguel Santos",
        kasarian: "Male",
        edad: 7,
        antasNgPaaralan: "Elementary",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Emmanuel Santos",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 50,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Basketball", "Scouting"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "Pills",
      saanTubig: "Manila Water",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["Asthma"],
      ilanKain: 3,
      ilanLigo: 2,
      ipon: false,
      utang: true,
      dswd: true,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
  {
    nanay: {
      pangalan: "Luisa Cruz",
      palayaw: "Lulu",
      kasarian: "Female",
      edad: 34,
      birthday: "1989-02-12",
      lugarNgKapanganakan: "Manila",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Manila High School",
      tirahan: "Manila",
      probinsya: "Metro Manila",
      trabaho: "Vendor",
      kita: 12000,
      skillTraining: "Business Management",
      skills: "Sales, Marketing",
      dokumento: ["Voter's ID", "PhilHealth"],
    },
    tatay: {
      pangalan: "Pedro Cruz",
      palayaw: "Pete",
      kasarian: "Male",
      edad: 37,
      birthday: "1986-08-10",
      lugarNgKapanganakan: "Manila",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "University of the East",
      tirahan: "Manila",
      probinsya: "Metro Manila",
      trabaho: "Driver",
      kita: 18000,
      skillTraining: "Driving",
      skills: "Navigation, Mechanics",
      dokumento: ["Driver's License", "SSS"],
    },
    child: {
      program: "Home Care",
      caseNo: 1002,
      pangalan: "Isabella Cruz",
      edad: 10,
      birthday: "2013-11-05",
      relihiyon: "Christian",
      antasNgPaaralan: "Elementary",
      palayaw: "Bella",
      kasarian: "Female",
      lugarNgKapanganakan: "Manila",
      hulingPaaralangPinasukan: "Manila Elementary School",
      tirahan: "Manila",
      problema: ["Frequent Absenteeism"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "BCG",
      initialNaItsura: ["Long hair", "Light skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Manila LGU" },
      nanay: "Luisa Cruz",
      tatay: "Pedro Cruz",
      kapatid: ["Sophia Cruz", "Lucas Cruz"], // Siblings will be inserted separately
      goalsAchieved: ["Improved attendance"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Sophia Cruz",
        kasarian: "Female",
        edad: 8,
        antasNgPaaralan: "Elementary",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "Lucas Cruz",
        kasarian: "Male",
        edad: 6,
        antasNgPaaralan: "Preschool",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Isabella Cruz",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 40,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Arts and Crafts", "Dance"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "None",
      saanTubig: "Local Well",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["None"],
      ilanKain: 3,
      ilanLigo: 2,
      ipon: true,
      utang: false,
      dswd: true,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
  {
    nanay: {
      pangalan: "Carmen Reyes",
      palayaw: "Carmie",
      kasarian: "Female",
      edad: 38,
      birthday: "1985-04-22",
      lugarNgKapanganakan: "Cavite",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "Cavite State University",
      tirahan: "Cavite",
      probinsya: "Cavite",
      trabaho: "Accountant",
      kita: 25000,
      skillTraining: "Financial Management",
      skills: "Accounting, Tax Preparation",
      dokumento: ["Voter's ID", "PhilHealth"],
    },
    tatay: {
      pangalan: "Jose Reyes",
      palayaw: "Joe",
      kasarian: "Male",
      edad: 42,
      birthday: "1981-09-13",
      lugarNgKapanganakan: "Cavite",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Cavite National High School",
      tirahan: "Cavite",
      probinsya: "Cavite",
      trabaho: "Security Guard",
      kita: 15000,
      skillTraining: "Security Training",
      skills: "Surveillance, Emergency Response",
      dokumento: ["SSS ID", "Police Clearance"],
    },
    child: {
      program: "Community Based Program",
      caseNo: 1003,
      pangalan: "Daniel Reyes",
      edad: 9,
      birthday: "2014-02-20",
      relihiyon: "Christian",
      antasNgPaaralan: "Elementary",
      palayaw: "Danny",
      kasarian: "Male",
      lugarNgKapanganakan: "Cavite",
      hulingPaaralangPinasukan: "Cavite Elementary School",
      tirahan: "Cavite",
      problema: ["Frequent Cough"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "Polio",
      initialNaItsura: ["Curly hair", "Medium skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Cavite LGU" },
      nanay: "Carmen Reyes",
      tatay: "Jose Reyes",
      kapatid: ["Andrea Reyes", "David Reyes"], // Siblings will be inserted separately
      goalsAchieved: ["Improved health"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Andrea Reyes",
        kasarian: "Female",
        edad: 7,
        antasNgPaaralan: "Elementary",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "David Reyes",
        kasarian: "Male",
        edad: 5,
        antasNgPaaralan: "Preschool",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Daniel Reyes",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 30,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Soccer", "Art Club"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "None",
      saanTubig: "Local Well",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["Frequent Cough"],
      ilanKain: 3,
      ilanLigo: 1,
      ipon: false,
      utang: true,
      dswd: true,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
  {
    nanay: {
      pangalan: "Elena Mendoza",
      palayaw: "Lena",
      kasarian: "Female",
      edad: 32,
      birthday: "1991-06-05",
      lugarNgKapanganakan: "Davao City",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "Ateneo de Davao University",
      tirahan: "Davao City",
      probinsya: "Davao del Sur",
      trabaho: "Nurse",
      kita: 30000,
      skillTraining: "Nursing",
      skills: "Patient Care, First Aid",
      dokumento: ["Nursing License", "PhilHealth"],
    },
    tatay: {
      pangalan: "Carlos Mendoza",
      palayaw: "Carl",
      kasarian: "Male",
      edad: 35,
      birthday: "1988-03-25",
      lugarNgKapanganakan: "Davao City",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Davao National High School",
      tirahan: "Davao City",
      probinsya: "Davao del Sur",
      trabaho: "Delivery Driver",
      kita: 18000,
      skillTraining: "Logistics Management",
      skills: "Driving, Delivery Coordination",
      dokumento: ["Driver's License", "SSS"],
    },
    child: {
      program: "Community Based Program",
      caseNo: 1004,
      pangalan: "Joaquin Mendoza",
      edad: 8,
      birthday: "2015-09-10",
      relihiyon: "Christian",
      antasNgPaaralan: "Elementary",
      palayaw: "Quin",
      kasarian: "Male",
      lugarNgKapanganakan: "Davao City",
      hulingPaaralangPinasukan: "Davao Elementary School",
      tirahan: "Davao City",
      problema: ["None"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "DTP",
      initialNaItsura: ["Straight hair", "Tan skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Davao LGU" },
      nanay: "Elena Mendoza",
      tatay: "Carlos Mendoza",
      kapatid: ["Diego Mendoza", "Mariana Mendoza"], // Siblings will be inserted separately
      goalsAchieved: ["Improved health"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Diego Mendoza",
        kasarian: "Male",
        edad: 5,
        antasNgPaaralan: "Preschool",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "Mariana Mendoza",
        kasarian: "Female",
        edad: 3,
        antasNgPaaralan: "None",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Joaquin Mendoza",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 20,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Football", "Music Club"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "None",
      saanTubig: "Local Spring",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["None"],
      ilanKain: 3,
      ilanLigo: 1,
      ipon: false,
      utang: false,
      dswd: true,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
  {
    nanay: {
      pangalan: "Patricia Lopez",
      palayaw: "Trish",
      kasarian: "Female",
      edad: 30,
      birthday: "1993-11-15",
      lugarNgKapanganakan: "Quezon City",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "University of the East",
      tirahan: "Quezon City",
      probinsya: "Metro Manila",
      trabaho: "Account Executive",
      kita: 28000,
      skillTraining: "Sales Management",
      skills: "Negotiation, Marketing",
      dokumento: ["Voter's ID", "PhilHealth"],
    },
    tatay: {
      pangalan: "Luis Lopez",
      palayaw: "Lui",
      kasarian: "Male",
      edad: 32,
      birthday: "1991-06-25",
      lugarNgKapanganakan: "Quezon City",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Quezon City High School",
      tirahan: "Quezon City",
      probinsya: "Metro Manila",
      trabaho: "IT Technician",
      kita: 22000,
      skillTraining: "IT Support",
      skills: "Troubleshooting, Networking",
      dokumento: ["IT Certification", "SSS"],
    },
    child: {
      program: "Home Care",
      caseNo: 1005,
      pangalan: "Sofia Lopez",
      edad: 6,
      birthday: "2017-08-30",
      relihiyon: "Christian",
      antasNgPaaralan: "Preschool",
      palayaw: "Sofi",
      kasarian: "Female",
      lugarNgKapanganakan: "Quezon City",
      hulingPaaralangPinasukan: "Quezon City Preschool",
      tirahan: "Quezon City",
      problema: ["None"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "BCG",
      initialNaItsura: ["Curly hair", "Light skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Quezon City LGU" },
      nanay: "Patricia Lopez",
      tatay: "Luis Lopez",
      kapatid: ["Paolo Lopez", "Camila Lopez"], // Siblings will be inserted separately
      goalsAchieved: ["Learned to read"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Paolo Lopez",
        kasarian: "Male",
        edad: 4,
        antasNgPaaralan: "Preschool",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "Camila Lopez",
        kasarian: "Female",
        edad: 2,
        antasNgPaaralan: "None",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Sofia Lopez",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 25,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Art Class", "Dance"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "None",
      saanTubig: "Local Supply",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["None"],
      ilanKain: 3,
      ilanLigo: 2,
      ipon: true,
      utang: false,
      dswd: true,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
  {
    nanay: {
      pangalan: "Monica Villanueva",
      palayaw: "Nica",
      kasarian: "Female",
      edad: 29,
      birthday: "1994-04-19",
      lugarNgKapanganakan: "Baguio City",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "University of the Cordilleras",
      tirahan: "Baguio City",
      probinsya: "Benguet",
      trabaho: "Bank Teller",
      kita: 22000,
      skillTraining: "Customer Service",
      skills: "Cash Handling, Communication",
      dokumento: ["Bank ID", "PhilHealth"],
    },
    tatay: {
      pangalan: "Marco Villanueva",
      palayaw: "Marc",
      kasarian: "Male",
      edad: 31,
      birthday: "1992-12-08",
      lugarNgKapanganakan: "Baguio City",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Baguio City High School",
      tirahan: "Baguio City",
      probinsya: "Benguet",
      trabaho: "Chef",
      kita: 25000,
      skillTraining: "Culinary Arts",
      skills: "Cooking, Baking",
      dokumento: ["Chef Certification", "SSS"],
    },
    child: {
      program: "Community Based Program",
      caseNo: 1006,
      pangalan: "Gabriela Villanueva",
      edad: 8,
      birthday: "2015-03-18",
      relihiyon: "Christian",
      antasNgPaaralan: "Elementary",
      palayaw: "Gabby",
      kasarian: "Female",
      lugarNgKapanganakan: "Baguio City",
      hulingPaaralangPinasukan: "Baguio Elementary School",
      tirahan: "Baguio City",
      problema: ["Frequent Headaches"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "DTP",
      initialNaItsura: ["Straight hair", "Light skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Baguio LGU" },
      nanay: "Monica Villanueva",
      tatay: "Marco Villanueva",
      kapatid: ["Sebastian Villanueva", "Lucas Villanueva"], // Siblings will be inserted separately
      goalsAchieved: ["Learning to write"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Sebastian Villanueva",
        kasarian: "Male",
        edad: 6,
        antasNgPaaralan: "Preschool",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "Lucas Villanueva",
        kasarian: "Male",
        edad: 4,
        antasNgPaaralan: "None",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Gabriela Villanueva",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 35,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Art Class", "Drama"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "None",
      saanTubig: "Local Spring",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["Frequent Headaches"],
      ilanKain: 3,
      ilanLigo: 2,
      ipon: false,
      utang: true,
      dswd: false,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
  // Add remaining families to complete the 10 entries...
  {
    nanay: {
      pangalan: "Nina Navarro",
      palayaw: "Nina",
      kasarian: "Female",
      edad: 31,
      birthday: "1992-07-14",
      lugarNgKapanganakan: "Iloilo City",
      relihiyon: "Christian",
      antasNgPaaralan: "High School",
      hulingPaaralangPinasukan: "Iloilo National High School",
      tirahan: "Iloilo City",
      probinsya: "Iloilo",
      trabaho: "Sales Assistant",
      kita: 15000,
      skillTraining: "Sales Training",
      skills: "Customer Service, Merchandising",
      dokumento: ["Voter's ID", "PhilHealth"],
    },
    tatay: {
      pangalan: "Carlos Navarro",
      palayaw: "Carl",
      kasarian: "Male",
      edad: 34,
      birthday: "1989-02-10",
      lugarNgKapanganakan: "Iloilo City",
      relihiyon: "Christian",
      antasNgPaaralan: "College",
      hulingPaaralangPinasukan: "University of the Philippines Visayas",
      tirahan: "Iloilo City",
      probinsya: "Iloilo",
      trabaho: "Marketing Manager",
      kita: 30000,
      skillTraining: "Marketing Strategies",
      skills: "Digital Marketing, Brand Management",
      dokumento: ["Company ID", "SSS"],
    },
    child: {
      program: "Community Based Program",
      caseNo: 1007,
      pangalan: "Mateo Navarro",
      edad: 7,
      birthday: "2016-04-15",
      relihiyon: "Christian",
      antasNgPaaralan: "Elementary",
      palayaw: "Matt",
      kasarian: "Male",
      lugarNgKapanganakan: "Iloilo City",
      hulingPaaralangPinasukan: "Iloilo Elementary School",
      tirahan: "Iloilo City",
      problema: ["None"],
      allergy: "None",
      dokumento: ["Birth Certificate"],
      vaccine: "MMR",
      initialNaItsura: ["Straight hair", "Light skin"],
      kategorya: { pangalan: "Low Income", ngo: "Local NGO", lgu: "Iloilo LGU" },
      nanay: "Nina Navarro",
      tatay: "Carlos Navarro",
      kapatid: ["Natalia Navarro", "Julian Navarro"], // Siblings will be inserted separately
      goalsAchieved: ["Learned to write"],
    },
    siblings: [
      {
        kapatidIndex: 1,
        pangalan: "Natalia Navarro",
        kasarian: "Female",
        edad: 5,
        antasNgPaaralan: "Preschool",
        trabaho: "",
        kita: 0,
      },
      {
        kapatidIndex: 2,
        pangalan: "Julian Navarro",
        kasarian: "Male",
        edad: 3,
        antasNgPaaralan: "None",
        trabaho: "",
        kita: 0,
      },
    ],
    family: {
      bata: "Mateo Navarro",
      ilanNagaaral: 3, // including siblings
      ilanBaon: 30,
      saanGastosBaon: "School Canteen",
      schoolActivity: ["Football", "Arts and Crafts"],
      kainPasok: true,
      alsAttend: false,
      checkup: true,
      familyPlanningMethod: "None",
      saanTubig: "Local Supply",
      saanLaba: "At home",
      saanCR: "Shared",
      sakit: ["None"],
      ilanKain: 3,
      ilanLigo: 1,
      ipon: true,
      utang: false,
      dswd: true,
    },
    stats: {
      year: 2023,
      goals: {
        General: [{ label: "Increase school attendance", valueKey: 1 }],
        Goal1: [{ label: "Provide health checkups", valueKey: 1 }],
        Goal2: [{ label: "Encourage family planning", valueKey: 1 }],
        Goal3: [{ label: "Support low-income families", valueKey: 1 }],
      },
    },
  },
];

// function to insert sample data
const insertSampleData = async () => {
  try {
    // connect to MongoDB
    await mongoose.connect(mongoURI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("MongoDB connected");

    // clear existing data (optional)
    await Promise.all([
      Child.deleteMany({}),
      Parent.deleteMany({}),
      Family.deleteMany({}),
      Sibling.deleteMany({}),
      Stats.deleteMany({}),
      User.deleteMany({}),
    ]);
    console.log("Existing data cleared");

    for (const family of families) {
      // insert Parents
      const [nanay, tatay] = await Parent.insertMany([
        family.nanay,
        family.tatay,
      ]);
      console.log(`Parents inserted for ${family.child.pangalan}`);

      // insert Child
      const child = new Child(family.child);
      await child.save();
      console.log(`Child inserted: ${family.child.pangalan}`);

      // insert Siblings
      await Sibling.insertMany(family.siblings);
      console.log(`Siblings inserted for ${family.child.pangalan}`);

      // insert Family
      const familyData = new Family(family.family);
      await familyData.save();
      console.log(`Family data inserted for ${family.child.pangalan}`);

      // insert Stats
      const stats = new Stats(family.stats);
      await stats.save();
      console.log(`Stats inserted for ${family.child.pangalan}`);
    }

    // const user = new User({
    //   username: "user1",
    //   password: "password123", // In a real-world scenario, hash the password!
    //   userType: "admin",
    // });
    // await user.save();
    // console.log("User inserted");

    const users = [
      {
        username: "super",
        password: "super", 
        userType: "admin",
      },
      {
        username: "Aron_reyes",
        password: "user1234",
        userType: "user",
      },
      {
        username: "Bob_manalo",
        password: "user1234",
        userType: "user",
      },
      {
        username: "Cathy_Li",
        password: "user1234",
        userType: "user",
      },
      {
        username: "Daren_So",
        password: "user1234",
        userType: "user",
      },
      {
        username: "Elli_Zamora",
        password: "user1234",
        userType: "user",
      },
    ];
    for (const user of users) {
      const newUser = new User(user);
      await newUser.save();
      console.log(`User inserted: ${user.username}`);
    }

    console.log("Sample data inserted successfully!");
  } catch (error) {
    console.error("Error inserting sample data:", error);
  } finally {
    // Close the connection
    await mongoose.connection.close();
    console.log("MongoDB connection closed");
  }
};
insertSampleData();
