export const Users = [
  {
    picture: null,
    pangalan: "Darryl Javier",
    program: "Community Based Program",
    palayaw: "Darealtube",
    edad: "18-24",
    kasarian: "Lalaki",
    birthday: "September 6, 2004",
    yearAdmitted: "2018",
    relihiyon: "Christian",
    status: "Active",
    caseNo: 8591273056712,
    goalsAchieved: ["Tutorial", "Assignment Help", "WASH", "Health Assistance"],
  },
  {
    picture: null,
    pangalan: "Andrea Dulin",
    program: "Community Based Program",
    palayaw: "Ann",
    edad: "18-24",
    kasarian: "Babae",
    birthday: "February 3, 2004",
    yearAdmitted: "2019",
    relihiyon: "Roman Catholic",
    status: "Active",
    caseNo: 9604573285916,
    goalsAchieved: [
      "Provisions of Medicines and Vitamins",
      "Reproductive Health Assistance",
      "Recreational Activities",
      "Talent Development",
    ],
  },
  {
    picture: null,
    pangalan: "Ralph Gabriel Bautista",
    program: "Home Care",
    palayaw: "Ralph",
    edad: "18-24",
    kasarian: "Lalaki",
    birthday: "",
    yearAdmitted: "2020",
    relihiyon: "",
    status: "Deleted",
    caseNo: 7694037691028,
    goalsAchived: [
      "Skills Training and Job Hunting",
      "Learning Session",
      "Assignment Help",
      "Tutorial",
      "Provision of Meal",
    ],
  },
  {
    picture: null,
    pangalan: "Jaryll Francis Salvador",
    program: "Home Care",
    palayaw: "Jaryll",
    edad: "18-24",
    kasarian: "Lalaki",
    birthday: "",
    yearAdmitted: "2021",
    relihiyon: "",
    status: "Active",
    caseNo: 8564638501782,
    goalsAchieved: [
      "Tutorial",
      "Document Processing",
      "School Visit",
      "Alternative Learning System (ALS)",
      "Provision of School Needs",
    ],
  },
];
